package com.sgcc.uap.share.electrician.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.sgcc.uap.share.customer.bo.OrderCustomerBeginPage;
import com.sgcc.uap.share.domain.OrderCustomer;
import com.sgcc.uap.share.electrician.bo.OrderElectricianBeginPage;

public interface ElectricainQueryOrderRepository extends JpaRepository<OrderElectricianBeginPage,String>,JpaSpecificationExecutor<OrderCustomer> {

	@Query(value="SELECT c.ADDRESS_LATITUDE,c.ADDRESS_LONGITUDE,c.APPOINTMENT_TIME,c.CREATE_TIME,c.CUSTOMER_ADDRESS,c.CUSTOMER_DESCRIVE,c.CUSTOMER_DESCRIVE_ICON, "
			+ " c.CUSTOMER_EVALUATE,c.CUSTOMER_EVALUATE_PHOTO,c.CUSTOMER_EVALUATE_TITLE,c.CUSTOMER_GRADE,c.CUSTOMER_ID,c.CUSTOMER_NAME,c.CUSTOMER_PHONENUMBER,"
			+ " c.CUSTOMER_PRICE,c.FINISH_TIME,c.IDENTITY_ID,c.ORDER_COMPLAINT_ID,c.ORDER_ID,c.ORDER_STATUS,c.ORDER_TYPE_ID,c.PAY_STATUS,c.REMARK_NUM1,"
			+ " c.REMARK_NUM2,c.REMARK_STR1,c.REMARK_STR2,c.REMARK_STR3,c.UPDATE_TIME,c.VOLTAGE,c.ORDER_FROM,c.CREATE_AREA_ID,c.REGISTERED_NUMBER,c.CUSTOMER_DESCRIVE_TITLE, "
			+ " e.ELECTRICIAN_DESCRIVE,e.ELECTRICIAN_DESCRIVE_ICON,e.ELECTRICIAN_PRICE,e.OTHER_ELECTRICIAN_ID,e.ORDER_CONTRACT,e.INSPECTION_REPORT,e.ELECTRICIAN_NAME, "
			+ " e.ELECTRICIAN_PHONENUMBER,e.CREATE_TIME AS ACCEPT_TIME,e.CONSTRUCTION_CONTENT ,e.ELECTRICIAN_PRICE,e.ORDER_ELECTRICIAN_ID "
			+"FROM order_customer  c "
			+"LEFT JOIN order_electrician e "
				+"ON c.ORDER_ID = e.ORDER_ID "
					+"WHERE e.ELECTRICIAN_ID = :electricianId AND e.ORDER_ELECTRICIAN_STATUS IN('1','4','5','8','9') "
			+ "UNION SELECT c.ADDRESS_LATITUDE,c.ADDRESS_LONGITUDE,c.APPOINTMENT_TIME,c.CREATE_TIME,c.CUSTOMER_ADDRESS,c.CUSTOMER_DESCRIVE,c.CUSTOMER_DESCRIVE_ICON, "
			+ " c.CUSTOMER_EVALUATE,c.CUSTOMER_EVALUATE_PHOTO,c.CUSTOMER_EVALUATE_TITLE,c.CUSTOMER_GRADE,c.CUSTOMER_ID,c.CUSTOMER_NAME,c.CUSTOMER_PHONENUMBER,"
			+ " c.CUSTOMER_PRICE,c.FINISH_TIME,c.IDENTITY_ID,c.ORDER_COMPLAINT_ID,c.ORDER_ID,c.ORDER_STATUS,c.ORDER_TYPE_ID,c.PAY_STATUS,c.REMARK_NUM1,"
			+ " c.REMARK_NUM2,c.REMARK_STR1,c.REMARK_STR2,c.REMARK_STR3,c.UPDATE_TIME,c.VOLTAGE,c.ORDER_FROM,c.CREATE_AREA_ID,c.REGISTERED_NUMBER,c.CUSTOMER_DESCRIVE_TITLE, "
			+ " eh.ELECTRICIAN_DESCRIVE,eh.ELECTRICIAN_DESCRIVE_ICON,eh.ELECTRICIAN_PRICE,eh.OTHER_ELECTRICIAN_ID,eh.ORDER_CONTRACT,eh.INSPECTION_REPORT,eh.ELECTRICIAN_NAME, "
			+ " eh.ELECTRICIAN_PHONENUMBER,eh.CREATE_TIME AS ACCEPT_TIME,eh.CONSTRUCTION_CONTENT ,eh.ELECTRICIAN_PRICE ,eh.ORDER_ELECTRICIAN_ID "
			+"FROM order_customer  c "
			+"LEFT JOIN order_electrician_his eh "
				+"ON c.ORDER_ID = eh.ORDER_ID "
					+"WHERE eh.ELECTRICIAN_ID = :electricianId AND eh.ORDER_ELECTRICIAN_STATUS IN('1','4','5','8','9') "
			+ "UNION SELECT ch.ADDRESS_LATITUDE,ch.ADDRESS_LONGITUDE,ch.APPOINTMENT_TIME,ch.CREATE_TIME,ch.CUSTOMER_ADDRESS,ch.CUSTOMER_DESCRIVE,ch.CUSTOMER_DESCRIVE_ICON, "
			+ " ch.CUSTOMER_EVALUATE,ch.CUSTOMER_EVALUATE_PHOTO,ch.CUSTOMER_EVALUATE_TITLE,ch.CUSTOMER_GRADE,ch.CUSTOMER_ID,ch.CUSTOMER_NAME,ch.CUSTOMER_PHONENUMBER,"
			+ " ch.CUSTOMER_PRICE,ch.FINISH_TIME,ch.IDENTITY_ID,ch.ORDER_COMPLAINT_ID,ch.ORDER_ID,ch.ORDER_STATUS,ch.ORDER_TYPE_ID,ch.PAY_STATUS,ch.REMARK_NUM1,"
			+ " ch.REMARK_NUM2,ch.REMARK_STR1,ch.REMARK_STR2,ch.REMARK_STR3,ch.UPDATE_TIME,ch.VOLTAGE,ch.ORDER_FROM,ch.CREATE_AREA_ID,ch.REGISTERED_NUMBER,ch.CUSTOMER_DESCRIVE_TITLE, "
			+ " e.ELECTRICIAN_DESCRIVE,e.ELECTRICIAN_DESCRIVE_ICON,e.ELECTRICIAN_PRICE,e.OTHER_ELECTRICIAN_ID,e.ORDER_CONTRACT,e.INSPECTION_REPORT,e.ELECTRICIAN_NAME, "
			+ " e.ELECTRICIAN_PHONENUMBER,e.CREATE_TIME AS ACCEPT_TIME,e.CONSTRUCTION_CONTENT ,e.ELECTRICIAN_PRICE ,e.ORDER_ELECTRICIAN_ID "
			+"FROM order_customer_his  ch "
			+"LEFT JOIN order_electrician e "
				+"ON ch.ORDER_ID = e.ORDER_ID "
					+"WHERE e.ELECTRICIAN_ID = :electricianId AND e.ORDER_ELECTRICIAN_STATUS IN('1','4','5','8','9') "
			+ "UNION SELECT ch.ADDRESS_LATITUDE,ch.ADDRESS_LONGITUDE,ch.APPOINTMENT_TIME,ch.CREATE_TIME,ch.CUSTOMER_ADDRESS,ch.CUSTOMER_DESCRIVE,ch.CUSTOMER_DESCRIVE_ICON, "
			+ " ch.CUSTOMER_EVALUATE,ch.CUSTOMER_EVALUATE_PHOTO,ch.CUSTOMER_EVALUATE_TITLE,ch.CUSTOMER_GRADE,ch.CUSTOMER_ID,ch.CUSTOMER_NAME,ch.CUSTOMER_PHONENUMBER,"
			+ " ch.CUSTOMER_PRICE,ch.FINISH_TIME,ch.IDENTITY_ID,ch.ORDER_COMPLAINT_ID,ch.ORDER_ID,ch.ORDER_STATUS,ch.ORDER_TYPE_ID,ch.PAY_STATUS,ch.REMARK_NUM1,"
			+ " ch.REMARK_NUM2,ch.REMARK_STR1,ch.REMARK_STR2,ch.REMARK_STR3,ch.UPDATE_TIME,ch.VOLTAGE,ch.ORDER_FROM,ch.CREATE_AREA_ID,ch.REGISTERED_NUMBER,ch.CUSTOMER_DESCRIVE_TITLE, "
			+ " eh.ELECTRICIAN_DESCRIVE,eh.ELECTRICIAN_DESCRIVE_ICON,eh.ELECTRICIAN_PRICE,eh.OTHER_ELECTRICIAN_ID,eh.ORDER_CONTRACT,eh.INSPECTION_REPORT,eh.ELECTRICIAN_NAME, "
			+ " eh.ELECTRICIAN_PHONENUMBER,eh.CREATE_TIME AS ACCEPT_TIME,eh.CONSTRUCTION_CONTENT ,eh.ELECTRICIAN_PRICE, eh.ORDER_ELECTRICIAN_ID "
			+"FROM order_customer_his  ch "
			+"LEFT JOIN order_electrician_his eh "
				+"ON ch.ORDER_ID = eh.ORDER_ID "
					+"WHERE eh.ELECTRICIAN_ID = :electricianId AND eh.ORDER_ELECTRICIAN_STATUS IN('1','4','5','8','9') "
			,nativeQuery=true)
	List<OrderElectricianBeginPage> findqQueryAllHaveDone(@Param("electricianId")String electricianId);

}
